// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBln3krtV0DlgjytMeyQNCpcOq29vfJ_iU',
    appId: '1:441564765916:web:81da80e733728ce0ba9e19',
    messagingSenderId: '441564765916',
    projectId: 'flutter-experiment-a826a',
    authDomain: 'flutter-experiment-a826a.firebaseapp.com',
    storageBucket: 'flutter-experiment-a826a.firebasestorage.app',
    measurementId: 'G-CFGXY6XRJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH7EM0eaLy4seySHeW-QoWxpAYFzAHjP0',
    appId: '1:441564765916:android:e0d57d8119ddd59bba9e19',
    messagingSenderId: '441564765916',
    projectId: 'flutter-experiment-a826a',
    storageBucket: 'flutter-experiment-a826a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnprz600CGaSVgI8wzy8EafJ2OmjeY3wg',
    appId: '1:441564765916:ios:15ba09eddd6f6607ba9e19',
    messagingSenderId: '441564765916',
    projectId: 'flutter-experiment-a826a',
    storageBucket: 'flutter-experiment-a826a.firebasestorage.app',
    androidClientId: '441564765916-4q0t55c0mb35h9qsv4ktke5ts0hkaheg.apps.googleusercontent.com',
    iosClientId: '441564765916-gnimbc12ek0m2b61kel7llfeqdt1a8f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExperiments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnprz600CGaSVgI8wzy8EafJ2OmjeY3wg',
    appId: '1:441564765916:ios:15ba09eddd6f6607ba9e19',
    messagingSenderId: '441564765916',
    projectId: 'flutter-experiment-a826a',
    storageBucket: 'flutter-experiment-a826a.firebasestorage.app',
    androidClientId: '441564765916-4q0t55c0mb35h9qsv4ktke5ts0hkaheg.apps.googleusercontent.com',
    iosClientId: '441564765916-gnimbc12ek0m2b61kel7llfeqdt1a8f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExperiments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBln3krtV0DlgjytMeyQNCpcOq29vfJ_iU',
    appId: '1:441564765916:web:423abc63cc6c323cba9e19',
    messagingSenderId: '441564765916',
    projectId: 'flutter-experiment-a826a',
    authDomain: 'flutter-experiment-a826a.firebaseapp.com',
    storageBucket: 'flutter-experiment-a826a.firebasestorage.app',
    measurementId: 'G-QVGSG5WZS8',
  );
}
