// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAVOBwlizepVnXrzpHBPFbzJPv8jYDmvI',
    appId: '1:605315188707:web:38dcd0b96d3ba8593982d6',
    messagingSenderId: '605315188707',
    projectId: 'chatstore-a9e70',
    authDomain: 'chatstore-a9e70.firebaseapp.com',
    storageBucket: 'chatstore-a9e70.firebasestorage.app',
    measurementId: 'G-LZ20NCL80H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzzruPQTg5b4MdZUgfm6cUG6u_fiBgF6E',
    appId: '1:605315188707:android:3a2f5de5651c9a843982d6',
    messagingSenderId: '605315188707',
    projectId: 'chatstore-a9e70',
    storageBucket: 'chatstore-a9e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRADtUVwrV_TyZ0_ncMQDUj-J_kEOOyw',
    appId: '1:605315188707:ios:050769139d86b5fb3982d6',
    messagingSenderId: '605315188707',
    projectId: 'chatstore-a9e70',
    storageBucket: 'chatstore-a9e70.firebasestorage.app',
    iosBundleId: 'com.example.flutterExperiments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRADtUVwrV_TyZ0_ncMQDUj-J_kEOOyw',
    appId: '1:605315188707:ios:050769139d86b5fb3982d6',
    messagingSenderId: '605315188707',
    projectId: 'chatstore-a9e70',
    storageBucket: 'chatstore-a9e70.firebasestorage.app',
    iosBundleId: 'com.example.flutterExperiments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAVOBwlizepVnXrzpHBPFbzJPv8jYDmvI',
    appId: '1:605315188707:web:3adb7164de36da7b3982d6',
    messagingSenderId: '605315188707',
    projectId: 'chatstore-a9e70',
    authDomain: 'chatstore-a9e70.firebaseapp.com',
    storageBucket: 'chatstore-a9e70.firebasestorage.app',
    measurementId: 'G-3Y6B92HW4J',
  );
}
